# Generated by Django 4.2.2 on 2023-10-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authentication',
            old_name='password_1',
            new_name='password',
        ),
    ]
