# Generated by Django 4.2.2 on 2023-10-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_rename_password_1_authentication_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=150)),
                ('song_name', models.CharField(max_length=150)),
                ('cover_image', models.ImageField(upload_to='cover_images')),
                ('audio_file', models.FileField(upload_to='audios')),
            ],
        ),
    ]
