# Generated by Django 4.2.2 on 2023-10-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0005_artiste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('song_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karaoke.song')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=10000)),
            ],
            bases=('karaoke.song',),
        ),
        migrations.DeleteModel(
            name='Artiste',
        ),
    ]
