# Generated by Django 4.2.2 on 2023-10-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0006_artist_delete_artiste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
