# Generated by Django 4.2.2 on 2023-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0007_delete_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
