# Generated by Django 4.2.2 on 2023-10-07 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0009_artist_remove_song_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='main',
        ),
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karaoke.artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
