# Generated by Django 4.2.2 on 2023-10-07 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0011_alter_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_ptr',
        ),
        migrations.AddField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='karaoke.artist'),
        ),
    ]
