# Generated by Django 4.2.2 on 2023-10-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0012_remove_song_artist_ptr_song_id_song_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_own', models.FileField(upload_to='audios')),
            ],
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
