# Generated by Django 4.2.2 on 2023-10-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0013_songs_alter_artist_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='ArtistSongs',
        ),
    ]
