# Generated by Django 4.2.2 on 2023-10-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0014_rename_songs_artistsongs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistSongs',
            new_name='ArtistSong',
        ),
    ]
