# Generated by Django 4.2.2 on 2023-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0016_favourite_delete_artistsong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
