# Generated by Django 4.2.2 on 2023-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0017_remove_song_id_song_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.AutoField(default='False', primary_key=True, serialize=False),
        ),
    ]
