# Generated by Django 4.2.2 on 2023-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0019_remove_favourite_id_favourite_fav_song_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='fav_song_id',
            field=models.AutoField(default='False', primary_key=True, serialize=False),
        ),
    ]
